**MAT216: Lab 4 Assignment**

Name: Aritra Ghose

Section: 7

ID: x

# Gauss-Jordan Elimination
Gauss-Jordan Elimination is an algorithm that can be used to solve systems of linear equations and to find the inverse of any invertible matrix.

# Reduced-row echelon form
The purpose of Gauss-Jordan Elimination is to use the three elementary row operations to convert a matrix into reduced-row echelon form. A matrix is in reduced-row echelon form, also known as row canonical form, if the following conditions are satisfied:

1. All rows with only zero entries are at the bottom of the matrix
2. The
first nonzero entry in a row, called the leading entry or the pivot, of each nonzero row is to the right of the leading entry of the row above it.
3. The leading entry, also known as the pivot, in any nonzero row is 1.
4.All other entries in the column containing a leading 1 are zeroes.

Solve the following system by the Gauss-Jordan method.

$$2x+y+2z=10$$

$$x+2y+z=8$$

$$3x+y−z=2$$

So, the augmented matrix would be -

\begin{bmatrix}
  2 & 1 & 2 & 10\\
  1 & 2 & 1 & 8\\
  3 & 1 & -1 & 2\\
\end{bmatrix}

$$=
\begin{bmatrix}
  2 & 1 & 2 & 10\\
  0 & 1.5 & 0 & 3\\
  3 & 1 & -1 & 2\\
\end{bmatrix}$$

$$=
\begin{bmatrix}
  2 & 1 & 2 & 10\\
  0 & 1.5 & 0 & 3\\
  0 & -0.5 & -4 & -13\\
\end{bmatrix}$$

$$=
\begin{bmatrix}
  2 & 0 & 2 & 8\\
  0 & 1.5 & 0 & 3\\
  0 & -0.5 & -4 & -13\\
\end{bmatrix}$$

$$=
\begin{bmatrix}
  2 & 0 & 2 & 8\\
  0 & 1.5 & 0 & 3\\
  0 & 0 & -4 & -12\\
\end{bmatrix}$$

$$=\begin{bmatrix}
  2 & 0 & 0 & 2\\
  0 & 1.5 & 0 & 3\\
  0 & 0 & -4 & -12\\
\end{bmatrix}$$
So,
$$ x = \frac{2}{2}\ = 1\hspace{.25cm} ,\hspace{.25cm} y = \frac{3}{1.5}\ = 2 \hspace{.25cm}, \hspace{.25cm}z = \frac{-12}{-4}\ = 3$$

In [ ]:
from numpy import matrix, linalg
import numpy as np

a = np.array([[2.0, 1.0, 2.0, 10.0],
              [1.0, 2.0, 1.0, 8.0],
              [3.0, 1.0, -1.0, 2.0]])


rows, columns = np.shape(a)
n = columns - 1

x = np.zeros(n)

for i in range(n):
    if a[i][i] == 0:
        break
    for j in range(n):
      if (i != j):
        ratio = a[j][i]/a[i][i]
        for k in range(n+1):
          a[j][k] = a[j][k] - (ratio * (a[i][k]))

print("After Gauss-Jordan Elimination: \n", a, "\n")


for i in range(n):
    x[i] = a[i][n]/a[i][i]



# Output

print(f"So, [x, y, z] = {x}")


After Gauss-Jordan Elimination: 
 [[  2.    0.    0.    2. ]
 [  0.    1.5   0.    3. ]
 [  0.    0.   -4.  -12. ]] 

So, [x, y, z] = [1. 2. 3.]


**Solve the following problem using Gauss Jordan Elimination method**

Star Cineplex charges 300 taka for regular tickets and 350 taka for premium tickets. If the production sold 140 tickets for its opening night and made 45,050 taka in ticket sales, how many of each type of tickets were sold?

In [ ]:
#write your code here

# From the given scenario, we can build the system of linear equations
# Let, x = number of regular tickets  and y = number of premium tickets

# So,
# x + y = 140     ----------------- (1)
# 300x + 350y = 45050     --------- (2)

augMat = np.array([[1.0, 1.0, 140.0],
                   [300.0, 350.0, 45050.0]])

print("So, the augmented matrix: \n", augMat)

rows, columns = np.shape(augMat)
n = columns - 1

x = np.zeros(n)

for i in range(n):
    if (augMat[i][i] == 0):
        break
    for j in range(n):
      if (i != j):
        ratio = augMat[j][i]/augMat[i][i]
        for k in range(n+1):
          augMat[j][k] = augMat[j][k] - (ratio * (augMat[i][k]))

print("\n \n After Gauss-Jordan Elimination: \n", augMat, "\n")


for i in range(n):
    x[i] = augMat[i][n]/augMat[i][i]


print(f"So, [x, y] = {x} \n")

print(f"So, {int(x[0])} regular tickets and {int(x[1])} premium tickets were sold.  (ans)")

So, the augmented matrix: 
 [[1.000e+00 1.000e+00 1.400e+02]
 [3.000e+02 3.500e+02 4.505e+04]]

 
 After Gauss-Jordan Elimination: 
 [[1.00e+00 0.00e+00 7.90e+01]
 [0.00e+00 5.00e+01 3.05e+03]] 

So, [x, y] = [79. 61.] 

So, 79 regular tickets and 61 premium tickets were sold.  (ans)
